#!/bin/bash
if [ x"$1" == x ]
then
	echo "usage: ./doall commit-comment"
	exit
fi
cd ~/Dropbox/JudyWeb/MyWeb
echo "git status:"
git status
echo -n "ok to pull? [ctrl-C for no]";read x
git pull
echo "Adding everything, to get new files..."
git add .
echo -n "ok to commit? [ctrl-C for no]";read x
if [ x"$1" != x ]
then
	git commit -a -m "$1"
else
	git commit -a
fi
# echo -n "ok to push? [ctrl-C for no]";read x
# git push
cp -R pdf ~/Dropbox/JudyWeb/JKAY-GitHub.github.io
echo "Running Hugo..."
../hugo -d ~/Dropbox/JudyWeb/JKAY-GitHub.github.io

cd ~/Dropbox/JudyWeb/JKAY-GitHub.github.io 
echo "Changing to JKAY-GitHub.github.io and running git pull"
git pull
echo "Adding everything, to get new files..."
git add .
echo -n "ok to commit? [ctrl-C for no]";read x
if [ x"$1" != x ]
then
	git commit -a -m "$1"
else
	git commit -a
fi
echo -n "ok to push? [ctrl-C for no]";read x
git push

echo "----------- all done -----------"

